Repository x1-company/be14-4th-x1-GROO-BE, pull requests merged in 2025-04, with the labels that each got.

#10 🔨 fix: user entity, token 수정
  src/main/java/com/x1/groo/security/dto/TokenDTO.java
  src/main/java/com/x1/groo/security/jwt/TokenProvider.java
  src/main/java/com/x1/groo/security/service/AuthService.java
  src/main/java/com/x1/groo/security/vo/LoginRequestVO.java
  src/main/java/com/x1/groo/user/aggregate/Role.java
  src/main/java/com/x1/groo/user/aggregate/UserEntity.java
  src/main/java/com/x1/groo/user/service/UserServiceImpl.java
Labels: 🚑 fix

#6 🌟 feat: 분리되어있던 ai 서버를 백엔드 서버로 통합 완료.
  build.gradle
  src/main/java/com/x1/groo/ai/controller/EmotionController.java
  src/main/java/com/x1/groo/ai/dto/EmotionRequestDTO.java
  src/main/java/com/x1/groo/ai/dto/EmotionResponseDTO.java
  src/main/java/com/x1/groo/ai/service/EmotionService.java
  src/main/java/com/x1/groo/ai/service/EmotionServiceImpl.java
Labels: ✨ Feature

#12 🌟 feat: 배치된 아이템 회수 기능 구현
  src/main/java/com/x1/groo/common/JwtUtil.java
  src/main/java/com/x1/groo/forest/emotion/command/application/controller/CommandEmotionForestController.java
  src/main/java/com/x1/groo/forest/emotion/command/application/service/CommandEmotionForestService.java
  src/main/java/com/x1/groo/forest/emotion/command/application/service/CommandEmotionForestServiceImpl.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/aggregate/PlacementEntity.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/aggregate/UserItemEntity.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/repository/PlacementRepository.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/repository/UserItemRepository.java
Labels: ✨ Feature

#18 🌟 feat: 해당 숲의 아이템 전체 회수 기능 구현
  src/main/java/com/x1/groo/forest/emotion/command/application/controller/CommandEmotionForestController.java
  src/main/java/com/x1/groo/forest/emotion/command/application/service/CommandEmotionForestService.java
  src/main/java/com/x1/groo/forest/emotion/command/application/service/CommandEmotionForestServiceImpl.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/repository/PlacementRepository.java
Labels: ✨ Feature

#20 🔨 refactor: Security 인증 실패/권한 실패 예외 수정
  src/main/java/com/x1/groo/forest/mate/query/service/MateServiceImpl.java
  src/main/java/com/x1/groo/security/config/SecurityConfig.java
  src/main/java/com/x1/groo/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/x1/groo/security/jwt/JwtAuthenticationEntryPoint.java
Labels: 🔨 Refactor, ✨ Feature

#22 🔨 fix: 방명록 리스트 조회용 DTO 추가 및 Controller 코드 수정
  src/main/java/com/x1/groo/forest/emotion/query/controller/QueryForestEmotionController.java
  src/main/java/com/x1/groo/forest/emotion/query/dto/QueryForestEmotionMailboxDTO.java
  src/main/java/com/x1/groo/forest/emotion/query/dto/QueryForestEmotionMailboxListDTO.java
  src/main/java/com/x1/groo/forest/emotion/query/dto/QueryForestEmotionUserItemDTO.java
  src/main/java/com/x1/groo/forest/emotion/query/repository/QueryForestEmotionMapper.java
  src/main/java/com/x1/groo/forest/emotion/query/service/QueryForestEmotionService.java
  src/main/java/com/x1/groo/forest/emotion/query/service/QueryForestEmotionServiceImpl.java
  src/main/resources/com/x1/groo/forest/emotion/query/repository/QueryForestEmotionMapper.xml
Labels: ✨ Feature

#24 🔨 fix: 기억의 조각 조회 오류 수정
  src/main/resources/com/x1/groo/forest/emotion/query/repository/QueryForestEmotionMapper.xml
Labels: 🚑 fix

#25 🌟 feat: 아이템 배치 로직 구현
  src/main/java/com/x1/groo/forest/emotion/command/application/controller/CommandEmotionForestController.java
  src/main/java/com/x1/groo/forest/emotion/command/application/service/CommandEmotionForestService.java
  src/main/java/com/x1/groo/forest/emotion/command/application/service/CommandEmotionForestServiceImpl.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/aggregate/ForestEntity.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/aggregate/PlacementEntity.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/aggregate/UserEntity.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/aggregate/UserItemEntity.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/repository/ForestRepository.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/repository/UserItemRepository.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/repository/UserRepository.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/vo/RequestPlacementVO.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/vo/RequestReplacementVO.java
Labels: ✨ Feature

#29 🌟 feat: 카테고리 별 감정 아이템 랜덤으로 추출하는 로직 구현
  src/main/java/com/x1/groo/item/controller/ItemController.java
  src/main/java/com/x1/groo/item/dto/CategoryDTO.java
  src/main/java/com/x1/groo/item/dto/CategoryEmotionItemDTO.java
  src/main/java/com/x1/groo/item/repository/ItemMapper.java
  src/main/java/com/x1/groo/item/service/ItemService.java
  src/main/java/com/x1/groo/item/service/ItemServiceImpl.java
  src/main/resources/com/x1/groo/item/repository/ItemMapper.xml
Labels: ✨ Feature

#32 🌟 feat: 유저가 참여중인 우정의 숲 리스트 조회
  src/main/java/com/x1/groo/forest/mate/query/controller/MateController.java
  src/main/java/com/x1/groo/forest/mate/query/dao/MateMapper.java
  src/main/java/com/x1/groo/forest/mate/query/dto/DiaryByDateDTO.java
  src/main/java/com/x1/groo/forest/mate/query/dto/MateForestResponseDTO.java
  src/main/java/com/x1/groo/forest/mate/query/service/MateService.java
  src/main/java/com/x1/groo/forest/mate/query/service/MateServiceImpl.java
  src/main/resources/com/x1/groo/forest/mate/query/dao/MateMapper.xml
Labels: ✨ Feature

#33 🌟 feat: 방명록 작성 로직 구현
  src/main/java/com/x1/groo/forest/emotion/command/application/controller/CommandEmotionForestController.java
  src/main/java/com/x1/groo/forest/emotion/command/application/service/CommandEmotionForestService.java
  src/main/java/com/x1/groo/forest/emotion/command/application/service/CommandEmotionForestServiceImpl.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/aggregate/MailboxEntity.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/repository/MailboxRepository.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/vo/RequestMailboxVO.java
Labels: ✨ Feature

#39 🌟 feat: 일기 등록
  src/main/java/com/x1/groo/ai/service/EmotionServiceImpl.java
  src/main/java/com/x1/groo/diary/controller/DiaryController.java
  src/main/java/com/x1/groo/diary/dto/DiaryRequestDTO.java
  src/main/java/com/x1/groo/diary/entity/Diary.java
  src/main/java/com/x1/groo/diary/entity/DiaryEmotion.java
  src/main/java/com/x1/groo/diary/repository/DiaryEmotionRepository.java
  src/main/java/com/x1/groo/diary/repository/DiaryRepository.java
  src/main/java/com/x1/groo/diary/service/DiaryService.java
  src/main/java/com/x1/groo/diary/service/DiaryServiceImpl.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/aggregate/EmotionSharedForestEntity.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/repository/EmotionSharedForestRepository.java
Labels: ✨ Feature

#42 🌟 feat: 우정의 숲 탈퇴 및 삭제기능 구현
  src/main/java/com/x1/groo/forest/mate/command/application/controller/CommandMateController.java
  src/main/java/com/x1/groo/forest/mate/command/application/service/CommandMateService.java
  src/main/java/com/x1/groo/forest/mate/command/application/service/CommandMateServiceImpl.java
  src/main/java/com/x1/groo/forest/mate/command/domain/repository/SharedForestRepository.java
  src/main/java/com/x1/groo/forest/mate/command/domain/vo/QuitForestCommand.java
  src/main/java/com/x1/groo/security/config/SecurityConfig.java
Labels: ✨ Feature

#34 🌟 feat: 숲 상세 조회 기능 구현
  src/main/java/com/x1/groo/forest/emotion/query/controller/QueryForestEmotionController.java
  src/main/java/com/x1/groo/forest/emotion/query/dto/PlacementDTO.java
  src/main/java/com/x1/groo/forest/emotion/query/dto/QueryForestEmotionDetailDTO.java
  src/main/java/com/x1/groo/forest/emotion/query/repository/QueryForestEmotionMapper.java
  src/main/java/com/x1/groo/forest/emotion/query/service/QueryForestEmotionService.java
  src/main/java/com/x1/groo/forest/emotion/query/service/QueryForestEmotionServiceImpl.java
  src/main/resources/com/x1/groo/forest/emotion/query/repository/QueryForestEmotionMapper.xml
Labels: ✨ Feature

#44 🌟 feat: 새 우정의 숲 만들기 구현
  src/main/java/com/x1/groo/forest/mate/command/application/controller/CommandMateController.java
  src/main/java/com/x1/groo/forest/mate/command/application/service/CommandMateService.java
  src/main/java/com/x1/groo/forest/mate/command/application/service/CommandMateServiceImpl.java
  src/main/java/com/x1/groo/forest/mate/command/domain/aggregate/BackgroundEntity.java
  src/main/java/com/x1/groo/forest/mate/command/domain/aggregate/MateForestEntity.java
  src/main/java/com/x1/groo/forest/mate/command/domain/aggregate/MateUserEntity.java
  src/main/java/com/x1/groo/forest/mate/command/domain/repository/BackgroundRepository.java
  src/main/java/com/x1/groo/forest/mate/command/domain/repository/ForestRepository.java
  src/main/java/com/x1/groo/forest/mate/command/domain/repository/UserRepository.java
  src/main/java/com/x1/groo/forest/mate/command/domain/vo/CreateMateForestRequest.java
Labels: ✨ Feature

#48 🌟 feat: 날짜별 조회에 감정 리스트 추가
  src/main/java/com/x1/groo/forest/mate/query/dto/DiaryByDateDTO.java
  src/main/resources/com/x1/groo/forest/mate/query/dao/MateMapper.xml
Labels: ✨ Feature

#50 🌟 feat: 숲 공개여부 전환 기능 구현
  src/main/java/com/x1/groo/forest/emotion/command/application/controller/CommandEmotionForestController.java
  src/main/java/com/x1/groo/forest/emotion/command/application/service/CommandEmotionForestService.java
  src/main/java/com/x1/groo/forest/emotion/command/application/service/CommandEmotionForestServiceImpl.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/vo/RequestPublicVO.java
Labels: ✨ Feature

#55 🔨 refactor: 유저의 숲 날짜별, 월별 조회시 임시 저장 일기 조회 불가능하게 수정
  src/main/resources/com/x1/groo/forest/mate/query/dao/MateMapper.xml
Labels: 🔨 Refactor

#62 🌟 feat: 일기 등록시 감정 및 카테고리별 감정 아이템 추출 완료
  src/main/java/com/x1/groo/diary/dto/DiaryRequestDTO.java
  src/main/java/com/x1/groo/diary/dto/DiaryResponseDTO.java
  src/main/java/com/x1/groo/diary/service/DiaryServiceImpl.java
  src/main/java/com/x1/groo/item/controller/UserItemStorageController.java
  src/main/java/com/x1/groo/item/domain/storage/aggregate/UserItemStorageEntity.java
  src/main/java/com/x1/groo/item/domain/storage/repository/UserItemStorageRepository.java
  src/main/java/com/x1/groo/item/service/UserItemStorageService.java
  src/main/java/com/x1/groo/item/service/UserItemStorageServiceImpl.java
  src/main/resources/com/x1/groo/item/repository/ItemMapper.xml
Labels: ✨ Feature

#68 🌟 feat: 임시 저장 상세 조회 구현 완료
  src/main/java/com/x1/groo/diary/controller/DiaryController.java
  src/main/java/com/x1/groo/diary/dto/DiarySaveDetailDTO.java
  src/main/java/com/x1/groo/diary/service/DiaryService.java
  src/main/java/com/x1/groo/diary/service/DiaryServiceImpl.java
Labels: ✨ Feature

#49 🔨 fix: ddl에 맞게 로직 수정 및 유저 검증 추가
  src/main/java/com/x1/groo/forest/emotion/command/application/service/CommandEmotionForestServiceImpl.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/aggregate/PlacementEntity.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/aggregate/UserItemEntity.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/repository/PlacementRepository.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/repository/UserItemRepository.java
Labels: ✨ Feature

#74 🌟 feat: 일기 수정 기능 구현
  src/main/java/com/x1/groo/diary/controller/DiaryController.java
  src/main/java/com/x1/groo/diary/dto/DiaryUpdateRequestDTO.java
  src/main/java/com/x1/groo/diary/dto/DiaryUpdateResponseDTO.java
  src/main/java/com/x1/groo/diary/service/DiaryService.java
  src/main/java/com/x1/groo/diary/service/DiaryServiceImpl.java
Labels: ✨ Feature

#76 🌟 feat: 임시 저장된 일기 등록 구현 완료
  src/main/java/com/x1/groo/diary/controller/DiaryController.java
  src/main/java/com/x1/groo/diary/service/DiaryService.java
  src/main/java/com/x1/groo/diary/service/DiaryServiceImpl.java
Labels: ✨ Feature

#80 🌟 feat: 감정의 숲 기록의 조각 조회에 forestId 추가
  src/main/java/com/x1/groo/forest/emotion/query/controller/QueryForestEmotionController.java
  src/main/java/com/x1/groo/forest/emotion/query/repository/QueryForestEmotionMapper.java
  src/main/java/com/x1/groo/forest/emotion/query/service/QueryForestEmotionService.java
  src/main/java/com/x1/groo/forest/emotion/query/service/QueryForestEmotionServiceImpl.java
  src/main/resources/com/x1/groo/forest/emotion/query/repository/QueryForestEmotionMapper.xml
Labels: ✨ Feature

#78 🚑 fix: 감정 일기 등록시 카테고리 값이 반환 안되는 오류 수정
  src/main/resources/com/x1/groo/item/repository/ItemMapper.xml
Labels: 🚑 fix

#81 🌟 feat: 감정의 숲 날짜별, 월별 일기조회 기능추가
  src/main/java/com/x1/groo/forest/emotion/query/controller/QueryForestEmotionController.java
  src/main/java/com/x1/groo/forest/emotion/query/dto/QueryForestEmotionDiaryByDateDTO.java
  src/main/java/com/x1/groo/forest/emotion/query/dto/QueryForestEmotionDiaryByMonthDTO.java
  src/main/java/com/x1/groo/forest/emotion/query/repository/QueryForestEmotionMapper.java
  src/main/java/com/x1/groo/forest/emotion/query/service/QueryForestEmotionService.java
  src/main/java/com/x1/groo/forest/emotion/query/service/QueryForestEmotionServiceImpl.java
  src/main/resources/com/x1/groo/forest/emotion/query/repository/QueryForestEmotionMapper.xml
Labels: ✨ Feature

#82 🌟 feat: 최신 감정의 숲 조회 기능 구현
  src/main/java/com/x1/groo/forest/emotion/query/controller/QueryForestEmotionController.java
  src/main/java/com/x1/groo/forest/emotion/query/dto/QueryForestEmotionListDTO.java
  src/main/java/com/x1/groo/forest/emotion/query/repository/QueryForestEmotionMapper.java
  src/main/java/com/x1/groo/forest/emotion/query/service/QueryForestEmotionService.java
  src/main/java/com/x1/groo/forest/emotion/query/service/QueryForestEmotionServiceImpl.java
  src/main/resources/com/x1/groo/forest/emotion/query/repository/QueryForestEmotionMapper.xml
Labels: ✨ Feature
