Repository x1-company/be14-4th-x1-GROO-BE, pull requests merged in 2025-05, with the labels that each got.

#89 🔨 fix: 우정의 숲 상세조회 오류 수정
  src/main/java/com/x1/groo/forest/mate/query/dao/MateMapper.java
  src/main/java/com/x1/groo/forest/mate/query/service/MateService.java
  src/main/java/com/x1/groo/forest/mate/query/service/MateServiceImpl.java
  src/main/resources/com/x1/groo/forest/mate/query/dao/MateMapper.xml
Labels: 🚑 fix

#84 👌 test: CICD test
  Dockerfile
  src/main/java/com/x1/groo/controller/GrooController.java
Labels: 🛡️ test

#86 🌟 feat: 감정의 숲 생성 기능 구현
  src/main/java/com/x1/groo/forest/emotion/command/application/controller/CommandEmotionForestController.java
  src/main/java/com/x1/groo/forest/emotion/command/application/service/CommandEmotionForestService.java
  src/main/java/com/x1/groo/forest/emotion/command/application/service/CommandEmotionForestServiceImpl.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/aggregate/ForestEntity.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/vo/RequestCreateVO.java
  src/main/java/com/x1/groo/forest/emotion/query/controller/QueryForestEmotionController.java
  src/main/java/com/x1/groo/forest/mate/command/application/service/CommandMateServiceImpl.java
  src/main/resources/com/x1/groo/forest/emotion/query/repository/QueryForestEmotionMapper.xml
Labels: ✨ Feature

#90 🚑 fix: mainEmotion, topEmotion 불안함 감정 매핑이 안되는 오류 수정
  src/main/java/com/x1/groo/ai/service/EmotionServiceImpl.java
Labels: 🚑 fix

#91 🌟 feat: 숲 이름 변경하기 구현
  src/main/java/com/x1/groo/forest/emotion/command/application/controller/CommandEmotionForestController.java
  src/main/java/com/x1/groo/forest/emotion/command/application/service/CommandEmotionForestService.java
  src/main/java/com/x1/groo/forest/emotion/command/application/service/CommandEmotionForestServiceImpl.java
  src/main/java/com/x1/groo/forest/emotion/command/domain/repository/ForestRepository.java
  src/main/java/com/x1/groo/forest/mate/query/controller/MateController.java
Labels: ✨ Feature

#93 🌟 feat: 회원가입 시 숲 자동 생성되게 구현 완료
  src/main/java/com/x1/groo/user/service/UserServiceImpl.java
Labels: ✨ Feature

#94 🚑 fix: 충돌 수정 및 일기 DTO 에 날짜 추가
  src/main/java/com/x1/groo/diary/dto/DiaryRequestDTO.java
  src/main/java/com/x1/groo/diary/service/DiaryServiceImpl.java
Labels: 🚑 fix

#97 fix: item update
  src/main/java/com/x1/groo/item/service/UserItemStorageServiceImpl.java
Labels: 🚑 fix

#102 🔨 refactor: 중복 엔티티 통합
  src/main/java/com/x1/groo/diary/entity/Diary.java
  src/main/java/com/x1/groo/forest/common/domain/AnnouncementEntity.java
  src/main/java/com/x1/groo/forest/common/domain/BackgroundEntity.java
  src/main/java/com/x1/groo/forest/common/domain/CategoryEntity.java
  src/main/java/com/x1/groo/forest/common/domain/DiaryEmotionEntity.java
  src/main/java/com/x1/groo/forest/common/domain/DiaryEntity.java
  src/main/java/com/x1/groo/forest/common/domain/ForestEntity.java
  src/main/java/com/x1/groo/forest/common/domain/ItemEntity.java
  src/main/java/com/x1/groo/forest/common/domain/MailboxEntity.java
  src/main/java/com/x1/groo/forest/common/domain/PlacementEntity.java
  src/main/java/com/x1/groo/forest/common/domain/SharedForestEntity.java
  src/main/java/com/x1/groo/forest/common/domain/UserEntity.java
  src/main/java/com/x1/groo/forest/common/domain/UserItemEntity.java
Labels: 🔨 Refactor

#103 🔨 refactor: 중복 repository 통합
  src/main/java/com/x1/groo/forest/common/domain/aggregate/AnnouncementEntity.java
  src/main/java/com/x1/groo/forest/common/domain/aggregate/BackgroundEntity.java
  src/main/java/com/x1/groo/forest/common/domain/aggregate/CategoryEntity.java
  src/main/java/com/x1/groo/forest/common/domain/aggregate/DiaryEmotionEntity.java
  src/main/java/com/x1/groo/forest/common/domain/aggregate/DiaryEntity.java
  src/main/java/com/x1/groo/forest/common/domain/aggregate/ForestEntity.java
  src/main/java/com/x1/groo/forest/common/domain/aggregate/ItemEntity.java
  src/main/java/com/x1/groo/forest/common/domain/aggregate/MailboxEntity.java
  src/main/java/com/x1/groo/forest/common/domain/aggregate/PlacementEntity.java
  src/main/java/com/x1/groo/forest/common/domain/aggregate/SharedForestEntity.java
  src/main/java/com/x1/groo/forest/common/domain/aggregate/UserEntity.java
  src/main/java/com/x1/groo/forest/common/domain/aggregate/UserItemEntity.java
  src/main/java/com/x1/groo/forest/common/domain/repository/AnnouncementRepository.java
  src/main/java/com/x1/groo/forest/common/domain/repository/BackgroundRepository.java
  src/main/java/com/x1/groo/forest/common/domain/repository/DiaryEmotionRepository.java
  src/main/java/com/x1/groo/forest/common/domain/repository/DiaryRepository.java
  src/main/java/com/x1/groo/forest/common/domain/repository/ForestRepository.java
  src/main/java/com/x1/groo/forest/common/domain/repository/MailboxRepository.java
  src/main/java/com/x1/groo/forest/common/domain/repository/PlacementRepository.java
  src/main/java/com/x1/groo/forest/common/domain/repository/SharedForestRepository.java
  src/main/java/com/x1/groo/forest/common/domain/repository/UserItemRepository.java
  src/main/java/com/x1/groo/forest/common/domain/repository/UserRepository.java
Labels: 🔨 Refactor
